function (add_test name src)
    add_executable(test_${name} ${src})
    target_compile_features(test_${name} PRIVATE cxx_std_23)
    target_link_libraries(test_${name} PRIVATE mlask)
    include_directories(${CMAKE_SOURCE_DIR}/include)
endfunction()

add_test(layer Layer.cpp)
add_test(fully_connected_layer FullyConnectedLayer.cpp)
add_test(one_neuron_network OneNeuronNetwork.cpp)
