function (add_test name src)
    set_source_files_properties(${src} PROPERTIES COMPILE_OPTIONS "-DDEBUG")
    add_executable(test_${name} ${src})
    target_compile_features(test_${name} PRIVATE cxx_std_23)
    target_link_libraries(test_${name} PRIVATE mlask)
    include_directories(${CMAKE_SOURCE_DIR}/include)
endfunction()

add_test(layer Layer.cpp)
add_test(fully_connected_layer FullyConnectedLayer.cpp)
add_test(one_neuron_network OneNeuronNetwork.cpp)
add_test(activation_function ActivationFunction.cpp)
add_test(exceptions exceptions.cpp)
add_test(iris iris.cpp)
